default: &default
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: mysql2
  username: root
  password: 
  host: localhost
  database: MobiliStore_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password: 
  host: localhost
  database: MobiliStore_test

production:
  <<: *default
  adapter: postgresql
  username: qesazfmhsxcxvl
  password: 44cda55c9aaa9a5c1344b755f5dbf15e9659381918b64f20c7b90ae85def8c2e
  host: ec2-54-235-80-137.compute-1.amazonaws.com
  port: 5432
  database: dafe7v5hnkkln2
